wal-g postgres wal-push command
wal-g/walg-daemon-client pull request #1
Opened 2023-06-16 08:09 UTC by sergey-arefev

the first client implementation to send commands to wal-g in daemon mode

2023-06-16 08:40 UTC, usernamedt requested changes

2023-06-16 08:40 UTC, usernamedt commented on README.md
> +lightweight client for [WAL-G](https://github.com/wal-g/wal-g/) daemon
We can provide a direct link to the functionality we're referring to (https://github.com/wal-g/wal-g/blob/master/docs/PostgreSQL.md#daemon)

2023-06-16 08:40 UTC, usernamedt commented on cmd/walg-daemon-client/main.go
> +	command		- command to send to the daemon: wal-push, wal-fetch
I would say `socket command [command_args]` would be more universal

2023-06-16 08:40 UTC, usernamedt commented on pkg/common/common.go
> +func SendCommand(opts *RunOptions) {
I guess this logic should belong to the `internal` package

2023-06-16 08:40 UTC, usernamedt commented on pkg/common/common.go
> +		log.Fatalf("unix socket set deadline error: %v\n", err)
we need to handle errors on the top level (e.g. `return err` instead of fatal)

2023-06-16 08:40 UTC, usernamedt commented on pkg/common/common.go
> +	CheckType    SocketMessageType = 'C'
I propose to extract these common message types [here](https://github.com/wal-g/wal-g/tree/master/pkg) and import it instead.

2023-06-20 06:18 UTC, sergey-arefev commented on cmd/walg-daemon-client/main.go
> +	command		- command to send to the daemon: wal-push, wal-fetch
changed to flags

2023-06-20 08:27 UTC, usernamedt commented on cmd/walg-daemon-client/main.go
> +	fs.StringVar(&opts.FileName, "file", "", "WAL file name (required for postgres specific commands: wal-push, wal-fetch)")
wal-push command requires single arg but wal-fetch require two args, so this single flag won't work. I suggest to stick with approach with args count varying between different commands, e.g.:
```
walg-daemon-client socket wal-push wal_path [flags]
walg-daemon-client socket wal-push wal_name destination_path [flags]
```

2023-06-21 13:49 UTC, usernamedt approved these changes

2023-06-21 13:50 UTC, merged